#!/bin/bash
#
# Copyright 2013 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Command-line tool for interacting with the Cloud Firestore emulator.

set -o errexit

declare -r FIRESTORE="$0"
declare -r FIRESTORE_DIR=$(dirname "${FIRESTORE}")
declare -r FIRESTORE_JAR="${FIRESTORE_DIR}/cloud-firestore-emulator.jar"

if [ ! -e "${FIRESTORE_JAR}" ]; then
    echo "${FIRESTORE_JAR} not found"
    exit 1
fi

# The Cloud Firestore emulator currently only supports English error messages
declare -r JVM_ENGLISH="-Duser.language=en"
declare -r JVM_FLAGS="${JVM_ENGLISH}"

${JAVA:="java"} ${JVM_FLAGS} -cp "${FIRESTORE_JAR}" com.google.cloud.datastore.emulator.firestore.CloudFirestore $*
