apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-to-in-testnamespace-for-ingress
  namespace: testnamespace
spec:
  policyTypes:
    - Ingress
  podSelector: {}
  ingress: 
    - {}