name: tag-release

on:
  push:
    branches:
      - 'release-*'
    paths:
      - version.txt

jobs:
  tag-release:
    if: ${{ github.repository == 'kubernetes-sigs/aws-iam-authenticator' }}
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.RELEASE_KEY }}"
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh

