gcloud components install app-engine-go
gcloud components install appctl
gcloud components install package-go-module
gcloud components install cbt
gcloud components install bigtable
gcloud components install cloud-datastore-emulator
gcloud components install cloud-firestore-emulator
gcloud components install pubsub-emulator
gcloud components install cloud-run-proxy
gcloud components install cloud_sql_proxy
gcloud components install docker-credential-gcr
gcloud components install kustomize
gcloud components install log-streaming
gcloud components install minikube
gcloud components install nomos
gcloud components install local-extract
gcloud components install skaffold
gcloud components install terraform-tools
gcloud components install anthos-auth
gcloud components install config-connector
gcloud components install enterprise-certificate-proxy
gcloud components install alpha
gcloud components install beta
gcloud components install app-engine-java
gcloud components install app-engine-php
gcloud components install app-engine-python
gcloud components install app-engine-python-extras
gcloud components install gke-gcloud-auth-plugin
gcloud components install kpt
gcloud components install kubectl
gcloud components install kubectl-oidc
gcloud components install pkg