apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: namespaces.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: Namespace
    plural: namespaces
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              type: string
            finalizers:
              items:
                type: string
              type: array
            name:
              type: string
          required:
          - cluster
          - name
          type: object
        status:
          properties:
            phase:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
