apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterroles.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: ClusterRole
    plural: clusterroles
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            aggregationRule:
              type: object
            apiVersion:
              type: string
            cluster:
              type: string
            kind:
              type: string
            metadata:
              type: object
            name:
              type: string
            rules:
              items:
                type: object
              type: array
          required:
          - rules
          - cluster
          - name
          type: object
        status:
          properties:
            status:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
