defaultPlatforms:
- linux/arm64
- linux/amd64

builds:
- id: cloud-controller-manager
  dir: .
  main: cmd/cloud-controller-manager
  ldflags:
  - -X k8s.io/component-base/version/verflag.programName=cloud-controller-manager

  - -X k8s.io/component-base/version.buildDate={{.Env.BUILD_DATE}}
  - -X k8s.io/component-base/version.gitCommit={{.Env.KUBE_GIT_COMMIT}}
  - -X k8s.io/component-base/version.gitMajor={{.Env.KUBE_GIT_MAJOR}}
  - -X k8s.io/component-base/version.gitMinor={{.Env.KUBE_GIT_MINOR}}
  - -X k8s.io/component-base/version.gitTreeState={{.Env.KUBE_GIT_TREE_STATE}}
  - -X k8s.io/component-base/version.gitVersion={{.Env.KUBE_GIT_VERSION}}

  - -X k8s.io/client-go/pkg/version.buildDate={{.Env.BUILD_DATE}}
  - -X k8s.io/client-go/pkg/version.gitCommit={{.Env.KUBE_GIT_COMMIT}}
  - -X k8s.io/client-go/pkg/version.gitMajor={{.Env.KUBE_GIT_MAJOR}}
  - -X k8s.io/client-go/pkg/version.gitMinor={{.Env.KUBE_GIT_MINOR}}
  - -X k8s.io/client-go/pkg/version.gitTreeState={{.Env.KUBE_GIT_TREE_STATE}}
  - -X k8s.io/client-go/pkg/version.gitVersion={{.Env.KUBE_GIT_VERSION}}

- id: gcp-controller-manager
  dir: .
  main: cmd/gcp-controller-manager
  ldflags:
  - -X k8s.io/component-base/version/verflag.programName=gcp-controller-manager

  - -X k8s.io/component-base/version.buildDate={{.Env.BUILD_DATE}}
  - -X k8s.io/component-base/version.gitCommit={{.Env.KUBE_GIT_COMMIT}}
  - -X k8s.io/component-base/version.gitMajor={{.Env.KUBE_GIT_MAJOR}}
  - -X k8s.io/component-base/version.gitMinor={{.Env.KUBE_GIT_MINOR}}
  - -X k8s.io/component-base/version.gitTreeState={{.Env.KUBE_GIT_TREE_STATE}}
  - -X k8s.io/component-base/version.gitVersion={{.Env.KUBE_GIT_VERSION}}

  - -X k8s.io/client-go/pkg/version.buildDate={{.Env.BUILD_DATE}}
  - -X k8s.io/client-go/pkg/version.gitCommit={{.Env.KUBE_GIT_COMMIT}}
  - -X k8s.io/client-go/pkg/version.gitMajor={{.Env.KUBE_GIT_MAJOR}}
  - -X k8s.io/client-go/pkg/version.gitMinor={{.Env.KUBE_GIT_MINOR}}
  - -X k8s.io/client-go/pkg/version.gitTreeState={{.Env.KUBE_GIT_TREE_STATE}}
  - -X k8s.io/client-go/pkg/version.gitVersion={{.Env.KUBE_GIT_VERSION}}
