# This pod template is used to launch the driver pod for the XGBoost example.
# The driver pod is launched in the same node group as the Spark driver.
# Make sure to update the availability zone and node group name to match your cluster.
# The toleration is required to allow the driver pod to be scheduled on the same node as the Spark driver.
apiVersion: v1
kind: Pod
metadata:
  name: xgboost-mortgage-driver
  namespace: emr-ml-team-a
spec:
  nodeSelector:
    NodeGroupType: "spark-driver-ca"
    topology.kubernetes.io/zone: "us-west-2b"

  tolerations:
    - key: "spark-driver-ca"
      operator: "Exists"
      effect: "NoSchedule"
