# This is the executor pod template for the XGBoost example.
# The executor pod is launched in the same node group as the Spark executor.
# Make sure to update the availability zone and node group name to match your cluster.
# The toleration is required to allow the executor pod to be scheduled on the same node as the Spark executor.
# /local1 is the local disk mount point on the node. This is used for shuffle data.
apiVersion: v1
kind: Pod
metadata:
  name: xgboost-mortgage-executor
  namespace: emr-ml-team-a

spec:
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1
        type: Directory

  nodeSelector:
    NodeGroupType: "spark-ubuntu-gpu-ca"
    topology.kubernetes.io/zone: "us-west-2b"

  containers:
    - name: spark-kubernetes-executor # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-1
          mountPath: /data1
          readOnly: false

  tolerations:
    - key: "spark-ubuntu-gpu-ca"
      operator: "Exists"
      effect: "NoSchedule"
