apiVersion: fleet.azure.com/v1alpha1
kind: ClusterResourcePlacement
metadata:
  name: hello-world
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: hello-world
  # If policy is unspecified, deploy to all the member clusters by default.
  # policy:
